### PR TITLE
Renames NeuroField to NFTsim

### PR DESCRIPTION
**Pull request by stuart-knock**
#141 
Completes the internal renaming of NeuroField to NFTsim.

With one exception, there should be no remaining use of any form of neurofield in the repository.

The only remaining use of NeuroField is a reference to a wiki page in the top level README. The wiki should be renamed before we make this change.

### CODE REVIEW

**Comment by pausz** [comment]
@stuart-knock I didn't find the reference to NeuroField on the top-level README. Which line?

**Comment by stuart-knock** [comment]
@pausz The wiki reference, line 68: https://github.com/BrainDynamicsUSYD/nftsim/wiki/How-to-contribute-code-to-NeuroField

**Comment by pausz** [comment]
@stuart-knock Thank you -- I completely missed that, I only did a case sensitive search for neurofield (searching for references to the old repo name).

**Comment by pausz** [comment]
I added documentation in the +nf functions; fixed some minor errors and updated TODOs. See #147 for future +nf tasks.

**Pull request merged**
