### PR TITLE
Review timeseries

### PR DESCRIPTION
**Pull request by stuart-knock**
#137 #138 #140 
Reviews Timeseries, standardising some of the notation and class naming. Also adds a simple Sine Timeseries and a PulseSigmoid Timeseries.

Example output of PulseSigmoid from the following .conf, comparing with PulseRect
```
Time: 15 Deltat: 0.0001
Nodes: 144

    Connection matrix:
From:  1 
To 1:  0

Population 1: Stimulation
Length: 0.5
 Stimulus: Superimpose: 2
 Stimulus: PulseRect - Onset: 2 Node: 72 Amplitude: 4.2 Width: 1.0 Period: 3 Pulses: 3
 Stimulus: PulseSigmoid - Onset: 2 Node: 42 Amplitude: 4.2 Width: 1.0 Period: 3 Pulses: 3

Output: Node: All Start: 0 Interval: 0.001 
Population: 1
Dendrite:  
Propagator:
Coupling: 
```
pulsesigmoid_pulserect

There are a few remaining issue noticed during the process, added two new issues: 
#143 #142 #145

### CODE REVIEW

**Comment by stuart-knock** [comment]
@pausz requested changes addressed by cc0f936
The two other recent commits (e467241 and 708ea8b) fix issues encountered while addressing your requested changes.

**Comment by pausz** [comment]
Check the Onset time of the PulseSigmoid and PulseRect:
screenshot from 2018-02-15 13-45-14

**Comment by pausz** [comment]
@stuart-knock Could you add and commit the images for the user manual please?

**Comment by stuart-knock** [comment]
@pausz  image files added with (91cf63e), apologies, I just forgot.

**Pull request merged**
